### PR TITLE
Added ChessOnChain to Nova wallet DApps

### PR DESCRIPTION
**Pull request by David-glitc**

### CODE REVIEW

**Comment by David-glitc** [comment]
@awesomepan @ERussel @rlaferla 

how soon can we expect an approval

**Comment by David-glitc** [comment]
Yes we're still On Testnet implementation

**Comment by leohar** [comment]
> Yes we're still On Testnet implementation

in this case i can only add it to dev and we can promote it when you will have prod implementation

**Review by leohar — APPROVED** [review]

**Comment by David-glitc** [comment]
So it can only be listed in Dev mode? We are in a Public beta testing although

**Pull request merged**
