### PR TITLE
Add GABE to HydraDX and Polkadot Asset Hub

### PR DESCRIPTION
**Pull request by arrudagates**
This PR adds the GABE token from Polkadot Asset Hub to Nova's registry under Polkadot Asset Hub and HydraDX.

### CODE REVIEW

**Review by antonkhvorov — APPROVED** [review]

**Comment by stepanLav** [comment]
@arrudagates 
Hello!
Thanks for PR, I have created it to the dev in order to went through QA verification
https://github.com/novasamatech/nova-utils/pull/2654

There is a chance that do you have an icon in .svg format? All Nova icons is stored in .svg and I'm afraid that png will make a problem on devices with different screens

**Comment by stepanLav** [comment]
We have adapt your png to svg, how you about it?
https://github.com/novasamatech/nova-utils/pull/2654/files#diff-098a5c726d5c0d48c065b57856fe08588de5eae9274ebc72a7c55b4eda55db8e

**Comment by arrudagates** [comment]
> We have adapetd your png to svg, how you about it?
> https://github.com/novasamatech/nova-utils/pull/2654/files#diff-098a5c726d5c0d48c065b57856fe08588de5eae9274ebc72a7c55b4eda55db8e
> 

Looks great, thank you! I used a PNG because I couldn't make the SVG myself, I'm happy to use the SVG you guys made.

**Comment by arrudagates** [comment]
Asset id is 1000062

**Review by stepanLav — APPROVED** [review]

**Pull request merged**
